### PR TITLE
Add grow_low and high to Box

### PR DESCRIPTION
**Pull request by dpgrote**
Implementing more things.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Excellent, thank you!

**Comment by ax3l** [comment]
Rebased to include https://github.com/AMReX-Codes/pyamrex/commit/6ef55913b74c70f6eb6ffc16f2d5ba5ad605f395

**Comment by dpgrote** [comment]
@ax3l I see the changes to the pyi files. Is this something that has to happen for every addition to the interface? Are these automatically generated?

**Comment by ax3l** [comment]
@dpgrote they are auto-generated and used for documentation (Sphinx) and interactive auto-completion purposes :)

**Pull request merged**
